# Generated by Django 4.2.8 on 2023-12-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=5)),
                ('age_group_pop', models.IntegerField()),
                ('n_yet_married', models.FloatField()),
                ('married_num', models.FloatField()),
                ('n_married_num', models.FloatField()),
                ('is_obese_rate', models.FloatField()),
                ('not_obese_rate', models.FloatField()),
                ('smoke_rate', models.FloatField()),
                ('not_smoke_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Height_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField()),
                ('ht_per', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Income_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_yr', models.IntegerField()),
                ('income_ratio', models.FloatField()),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_groups', to='bach_calc.age_ref')),
            ],
        ),
    ]
