version: 0.0
os: linux


files:
  - source: /
    destination: /home/ubuntu/portfolio_proj
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh 
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh 
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh  
      timeout: 300
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh  
      timeout: 300
      runas: ubuntu
 
