version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
        commands:
          - pip3 install -r portfolio_proj/hub/requirements.txt
        pre_build:
          commands:
            - echo "Changing to the app directory"
            - cd portfolio_proj/hub/
        build:
          commands:
            - echo "Running migrations"
            - python manage.py migrate
            - echo "Running tests"
            - python manage.py test
        post_build:
          commands:
            - echo Build completed on `date`
